services:
  - type: web
    plan: free
    name: dixitachatbot
    env: docker
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URL
        sync: false
      - key: OWNER_ID
        sync: false
      - key: SUPPORT_GRP
        sync: false
      - key: UPDATE_CHNL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: WEB_SERVICE
        value: "True"
      - key: PORT
        value: "8080"
